packages:
  # all packages in direct subdirs of packages/
  - 'packages/**/*'
  # all packages in subdirs of components/
  - 'dev/**/*'
  # tmp folder - this is used for integration tests
  - 'tmp/**/*'
  # exclude packages that are inside test directories
  - '!**/test/**'
